name: macos

on: 
  push:            # run on push events
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'
    branches:
      - '**'
    tags:
      - '*'
  pull_request:    # run on pull requests
    paths-ignore:  # but ignore everything in the docs subfolder 
      - 'docs/**'
  schedule:
    - cron:  '5 2 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-13]
    runs-on: ${{ matrix.os }}
#    runs-on: macos-11
    env:
      CCACHE_COMPILERTYPE: clang

    steps:
    - name: Cloning SUMO
      uses: actions/checkout@v3
      with:
        path: sumo
        fetch-depth: 0

    - name: Fetching SUMO tags
      run: |
        cd sumo
        git fetch --tags --force

    - name: Preparing Build System
      run: |
        brew install --cask xquartz
        brew install xerces-c fox proj gdal gl2ps ccache googletest
#        python3 -m pip install texttest

    - name: ccache
      if: github.event_name != 'schedule'
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Building SUMO
      run: |
        mkdir -p sumo/cmake-build 
        cd sumo/cmake-build 
        cmake ..
        make -j4

    - name: Building Traas
      run: |
        cd sumo/cmake-build 
        make traas

    - name: Installing SUMO
      run: |
        cd sumo/cmake-build 
        sudo make install

    - name: Building Examples and Tests
      run: |
        cd sumo/cmake-build
        make CTEST_OUTPUT_ON_FAILURE=1 examples test

    - name: Uploading artifacts (SUMO binaries)
      uses: actions/upload-artifact@v3
      with:
        name: macOS
        path: sumo/bin

    - name: Uploading FMI 2.0 FMU artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sumo-fmi2-darwin64
        path: sumo/bin/sumo-fmi2-darwin64.fmu
